### ISSUE TITLE
Fix execution on Ubuntu 20.04

### ISSUE THREAD

**Issue by ad-si** [feramhq/Perspec#13]
```txt
$ stack run -- fix images/doc.jpg
Loaded file images/doc.jpg (1500,880)
with orientation Normal
Starting the app …
freeglut (perspec): illegal glutInit() reinitialization attempt
```

Used build steps:

https://github.com/feramhq/Perspec/blob/63d1d37a185f85400ed03c7d8527f4becd2b9d8b/.github/workflows/main.yml#L46-L76

- [ ] Write answer to https://softwarerecs.stackexchange.com/questions/11282/software-to-straighten-an-oblique-rectangle-due-to-picture-perspective-to-2d-r

**Comment by ad-si** [comment]
- [ ] Write answer to https://softwarerecs.stackexchange.com/questions/11282/software-to-straighten-an-oblique-rectangle-due-to-picture-perspective-to-2d-r

**Comment by jaccokrijnen** [comment]
Trying to reproduce this problem. I get a slightly different error:

```
$ stack run -- fix ./images/doc.jpg 
Loaded file /home/jacco/projects/Perspec/images/doc.jpg (1500,880)
with a rotation of 0.0 degrees.
perspec: user error (unknown GLUT entry glutInit)
```

**Comment by jaccokrijnen** [comment]
After `apt` installing `freeglut3` The error changed to the one in the original post:

```
freeglut (perspec): illegal glutInit() reinitialization attempt
```

**Comment by ad-si** [comment]
`freeglut` and `libglfw` must be installed.
