### ISSUE TITLE
Buying license is not possible

### ISSUE THREAD

**Issue by cju77** [feramhq/Perspec#31]
Hello, how can i buy via PayPal? I tried to buy a license via the webpage (https://feram.gumroad.com/l/perspec) but it doesn't work because the fields are flickering after i entered some data. Further i have security concerns about to give my credit card data on this the site because it is not verified anywhere.

**Comment by ad-si** [comment]
Hi, thanks for your efforts!
The https://feram.gumroad.com/l/perspec page is powered by https://gumroad.com, which is a quite respectable company (https://en.wikipedia.org/wiki/Gumroad). So I assume that paying there is secure and reliable. Can you maybe try again? (Maybe also with another browser your current one has problems with the page)

**Comment by ad-si** [comment]
I'm glad it worked for you now. Thanks again for purchasing Perspec! 🙌
